'use strict';function x(g,a,b,c){g.v.mc(g.Za,a,b,c,void 0)}function D(g,a,b,c){g.v.qa?x(g,a,b,c):g.v.jf()._OnMessageFromDOM({type:"event",component:g.Za,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function E(g,a,b){g.v.B(g.Za,a,b)}function H(g,a){for(const [b,c]of a)E(g,b,c)}function K(g){g.Pb||(g.v.Ue(g.de),g.Pb=!0)}window.ec=class{constructor(g,a){this.v=g;this.Za=a;this.Pb=!1;this.de=()=>this.Ca()}ed(){}Ca(){}};function L(g){-1!==g.Na&&(self.clearTimeout(g.Na),g.Na=-1)}
window.Le=class{constructor(g,a){this.Mc=g;this.Cg=a;this.Na=-1;this.Qb=-Infinity;this.ee=()=>{this.Na=-1;this.Qb=Date.now();this.eb=!0;this.Mc();this.eb=!1};this.Nd=this.eb=!1}c(){L(this);this.ee=this.Mc=null}};"use strict";function M(g,a){const b=a.elementId,c=g.cc(b,a);g.Y.set(b,c);a.isVisible||(c.style.display="none");a=g.wc(c);a.addEventListener("focus",()=>{N(g,"elem-focused",b)});a.addEventListener("blur",()=>{N(g,"elem-blurred",b)});g.Kb&&document.body.appendChild(c)}
function O(g,a,b){E(g,a,c=>{const f=g.Y.get(c.elementId);return b(f,c)})}function N(g,a,b,c){c||(c={});c.elementId=b;x(g,a,c)}function P(g,a,b,c){c||(c={});c.elementId=b;D(g,a,c)}
window.jd=class extends self.ec{constructor(g,a){super(g,a);this.Y=new Map;this.Kb=!0;H(this,[["create",b=>M(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Kb&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Kb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Kb){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.Ua(c,b)}}],["focus",b=>{{const c=this.wc(this.Y.get(b.elementId));b.focus?c.focus():c.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);O(this,"get-element",b=>b)}cc(){throw Error("required override");}Ua(){throw Error("required override");
}wc(g){return g}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h){const d=document.createElement("script");d.async=!1;d.type="module";return h.Mg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;d.textContent=h.Pg+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=h;document.head.appendChild(d)})}let c=!1,f=!1;function m(){if(!c){try{new Worker("blob://",{get type(){f=!0}})}catch(h){}c=!0}return f}let n=
new Audio;const u={"audio/webm; codecs=opus":!!n.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!n.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!n.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!n.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!n.canPlayType("audio/mp4"),"audio/mpeg":!!n.canPlayType("audio/mpeg")};n=null;async function A(h){h=await B(h);return(new TextDecoder("utf-8")).decode(h)}function B(h){return new Promise((d,
k)=>{const l=new FileReader;l.onload=p=>d(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(h)})}const v=[];let w=0;window.RealFile=window.File;const C=[],G=new Map,y=new Map;let I=0;const F=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");F.push(h)};const J=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.Ta=class h{constructor(d){this.qa=d.Rg;this.oa=null;this.F="";this.Yb=d.Og;this.sb={};this.Ga=this.rb=null;
this.Nb=[];this.gb=this.K=this.La=null;this.Ka=-1;this.Hg=()=>this.Jf();this.Ja=[];this.C=d.fe;!this.qa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.qa=!1);J.has(this.C)&&this.qa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is currently disabled in WebViews. Reverting to DOM mode."),this.qa=!1);this.Sb=this.ha=null;"html5"!==this.C&&"playable-ad"!==this.C||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.B("runtime","cordova-fetch-local-file",k=>this.uf(k));this.B("runtime","create-job-worker",()=>this.vf());"cordova"===this.C?document.addEventListener("deviceready",()=>this.zd(d)):this.zd(d)}c(){this.sc();this.oa&&(this.oa=this.oa.onmessage=null);this.rb&&(this.rb.terminate(),this.rb=null);this.Ga&&(this.Ga.c(),this.Ga=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}od(){return g&&"cordova"===this.C}lc(){return g&&J.has(this.C)||navigator.standalone}async zd(d){"macos-wkwebview"===
this.C&&this.eg();if("playable-ad"===this.C){this.ha=self.c3_base64files;this.Sb={};await this.Ze();for(let l=0,p=d.Oa.length;l<p;++l){var k=d.Oa[l].toLowerCase();this.Sb.hasOwnProperty(k)?d.Oa[l]={Mg:!0,Pg:this.Sb[k]}:this.ha.hasOwnProperty(k)&&(d.Oa[l]=URL.createObjectURL(this.ha[k]))}}d.Ig?this.F=d.Ig:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));d.Tg&&(this.sb=d.Tg);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=
l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Ff(l));this.gb=new self.He(this);await Q(this.gb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.qa?await this.lf(d,k.port2):await this.kf(d,k.port2)}yc(d){d=this.sb.hasOwnProperty(d)?this.sb[d]:d.endsWith("/workermain.js")&&this.sb.hasOwnProperty("workermain.js")?this.sb["workermain.js"]:
"playable-ad"===this.C&&this.ha.hasOwnProperty(d.toLowerCase())?this.ha[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async dc(d,k,l){if(d.startsWith("blob:"))return new Worker(d,l);if(this.od()&&"file:"===location.protocol)return d=await this.ub(this.Yb+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();
return new Worker(URL.createObjectURL(d),l)}return new Worker(d,l)}va(){return Math.max(window.innerWidth,1)}ua(){return Math.max(window.innerHeight,1)}xd(d){var k=this.gb;return{baseUrl:this.F,windowInnerWidth:this.va(),windowInnerHeight:this.ua(),devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Ra(),projectData:d.Yg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Wg||
"",exportType:d.fe,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Xg,jobScheduler:{inputPort:k.Sc,outputPort:k.Zc,maxNumWorkers:k.Eg},supportedAudioFormats:u,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Yb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Yb+"opus.wasm.wasm",isiOSCordova:this.od(),isiOSWebView:this.lc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async lf(d,k){var l=this.yc(d.Sg);this.rb=await this.dc(l,this.F,{type:"module",name:"Runtime"});
this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.rb.postMessage(Object.assign(this.xd(d),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:d.dd||[],engineScripts:d.Oa,projectScripts:d.he,mainProjectScript:d.ge,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...R(this.gb)]);this.Nb=C.map(p=>new p(this));this.wd();self.c3_callFunction=(p,r)=>
this.La.mf(p,r);"preview"===this.C&&(self.goToLastErrorScript=()=>this.mc("runtime","go-to-last-error-script"))}async kf(d,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Nb=C.map(q=>new q(this));this.wd();var l=d.Oa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(d.dd)&&l.unshift(...d.dd);l=await Promise.all(l.map(q=>this.Cc(q)));await Promise.all(l.map(q=>b(q)));l=self.C3_ProjectScriptsStatus;
const p=d.ge,r=d.he;for(let [q,t]of r)if(t||(t=q),q===p)try{t=await this.Cc(t),await b(t),"preview"!==this.C||l[q]||this.Hd(q,"main script did not run to completion")}catch(z){this.Hd(q,z)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))t=await this.Cc(t),await b(t);"preview"===this.C&&"object"!==typeof self.Ug.Vg?(this.Gb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(d=Object.assign(this.xd(d),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:F}),this.Bd(),this.Ga=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Ga,d))}Hd(d,k){this.Gb();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Bd(){this.Gb()}Gb(){const d=window.Jg;d&&(d.parentElement.removeChild(d),window.Jg=
null)}async vf(){const d=await S(this.gb);return{outputPort:d,transferables:[d]}}jf(){if(this.qa)throw Error("not available in worker mode");return this.Ga}mc(d,k,l,p,r){this.oa.postMessage({type:"event",component:d,handler:k,dispatchOpts:p||null,data:l,responseId:null},r)}pd(d,k,l,p,r){const q=I++,t=new Promise((z,V)=>{y.set(q,{resolve:z,reject:V})});this.oa.postMessage({type:"event",component:d,handler:k,dispatchOpts:p||null,data:l,responseId:q},r);return t}["_OnMessageFromRuntime"](d){const k=
d.type;if("event"===k)return this.Af(d);if("result"===k)this.Nf(d);else if("runtime-ready"===k)this.Of();else if("alert-error"===k)this.Gb(),alert(d.message);else if("creating-runtime"===k)this.Bd();else throw Error(`unknown message '${k}'`);}Af(d){const k=d.component,l=d.handler,p=d.data,r=d.responseId;if(d=G.get(k))if(d=d.get(l)){var q=null;try{q=d(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==r&&this.Fb(r,!1,""+t);return}if(null===r)return q;q&&q.then?q.then(t=>this.Fb(r,
!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Fb(r,!1,""+t)}):this.Fb(r,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Fb(d,k,l){let p;l&&l.transferables&&(p=l.transferables);this.oa.postMessage({type:"result",responseId:d,isOk:k,result:l},p)}Nf(d){const k=d.responseId,l=d.isOk;d=d.result;const p=y.get(k);l?p.resolve(d):p.reject(d);y.delete(k)}B(d,k,l){let p=G.get(d);p||(p=new Map,
G.set(d,p));if(p.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);p.set(k,l)}static tb(d){if(C.includes(d))throw Error("DOM handler already added");C.push(d)}wd(){for(const d of this.Nb)if("runtime"===d.Za){this.La=d;return}throw Error("cannot find runtime DOM handler");}Ff(d){this.mc("debugger","message",d)}Of(){for(const d of this.Nb)d.ed()}static Ra(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||e)}static Id(d){e=!!d}Ue(d){this.Ja.push(d);
this.Kc()}bg(d){d=this.Ja.indexOf(d);if(-1===d)throw Error("invalid callback");this.Ja.splice(d,1);this.Ja.length||this.sc()}Kc(){-1===this.Ka&&this.Ja.length&&(this.Ka=requestAnimationFrame(this.Hg))}sc(){-1!==this.Ka&&(cancelAnimationFrame(this.Ka),this.Ka=-1)}Jf(){this.Ka=-1;for(const d of this.Ja)d();this.Kc()}ta(d){this.La.ta(d)}Ba(d){this.La.Ba(d)}Jc(){this.La.Jc()}Ab(d){this.La.Ab(d)}Ge(){return!!u["audio/webm; codecs=opus"]}async Ag(d){d=await this.pd("runtime","opus-decode",{arrayBuffer:d},
null,[d]);return new Float32Array(d)}Fe(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}nd(d){return!this.Fe(d)}async Cc(d){return"cordova"===this.C&&(d.startsWith("file:")||"file:"===location.protocol&&this.nd(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),d=await this.ub(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async uf(d){const k=d.filename;switch(d.as){case "text":return await this.ye(k);case "buffer":return await this.ub(k);
default:throw Error("unsupported type");}}hd(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,r=>{r.file(l,p)},p)})}async ye(d){d=await this.hd(d);return await A(d)}tc(){if(v.length&&!(8<=w)){w++;var d=v.shift();this.$e(d.filename,d.Qg,d.Lg)}}ub(d){return new Promise((k,l)=>{v.push({filename:d,Qg:p=>{w--;this.tc();k(p)},Lg:p=>{w--;this.tc();l(p)}});this.tc()})}async $e(d,k,l){try{const p=await this.hd(d),r=await B(p);
k(r)}catch(p){l(p)}}eg(){var d={type:"ready"};if("windows-webview2"===this.C)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.C)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async Ze(){const d=[];for(const [k,l]of Object.entries(this.ha))d.push(this.Ye(k,l));await Promise.all(d)}async Ye(d,k){if("object"===typeof k)this.ha[d]=new Blob([k.str],{type:k.type}),this.Sb[d]=k.str;else{let l=await this.gf(k);
l||(l=this.bf(k));this.ha[d]=l}}async gf(d){try{return await (await fetch(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}bf(d){d=this.Wf(d);return this.Xe(d.data,d.Ng)}Wf(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(k+1);k=d.substring(5,k).split(";");d=k[0]||
"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Ng:d,data:l}}Xe(d,k){var l=d.length;let p=l>>2,r=new Uint8Array(l),q=new Uint32Array(r.buffer,0,p),t,z;for(z=t=0;t<p;++t)q[t]=d.charCodeAt(z++)|d.charCodeAt(z++)<<8|d.charCodeAt(z++)<<16|d.charCodeAt(z++)<<24;for(l&=3;l--;)r[z]=d.charCodeAt(z),++z;return new Blob([r],{type:k})}}}"use strict";
{const g=self.Ta;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function n(e){return new Promise((h,d)=>{const k=document.createElement("link");k.onload=()=>h(k);k.onerror=l=>d(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function u(e){return new Promise((h,d)=>{const k=new Image;k.onload=()=>h(k);k.onerror=l=>d(l);k.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await u(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((h,d)=>{let k=new FileReader;k.onload=l=>h(l.target.result);k.onerror=l=>d(l);k.readAsText(e)})}async function v(e,h,d){if(!/firefox/i.test(navigator.userAgent))return await A(e);var k=await B(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const p=l.getAttribute("width"),r=l.getAttribute("height");if(!p.includes("%")&&!r.includes("%"))return await A(e)}l.setAttribute("width",h+"px");l.setAttribute("height",d+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await A(e)}function w(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function y(e){G.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function I(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,d,k,l){e=await v(e,h,d);const p=document.createElement("canvas");p.width=k;p.height=l;p.getContext("2d").drawImage(e,0,0,h,d);return p};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function J(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.tb(class extends self.ec{constructor(e){super(e,"runtime");this.Sd=!0;this.Ma=-1;this.ad="any";this.Jd=this.Kd=!1;this.Vc=
this.ob=this.xa=null;e.B("canvas","update-size",k=>this.Tf(k));e.B("runtime","invoke-download",k=>this.Ef(k));e.B("runtime","raster-svg-image",k=>this.Kf(k));e.B("runtime","get-svg-image-size",k=>this.Cf(k));e.B("runtime","set-target-orientation",k=>this.Rf(k));e.B("runtime","register-sw",()=>this.Lf());e.B("runtime","post-to-debugger",k=>this.Dd(k));e.B("runtime","go-to-script",k=>this.Dd(k));e.B("runtime","before-start-ticking",()=>this.sf());e.B("runtime","debug-highlight",k=>this.wf(k));e.B("runtime",
"enable-device-orientation",()=>this.We());e.B("runtime","enable-device-motion",()=>this.Ve());e.B("runtime","add-stylesheet",k=>this.qf(k));e.B("runtime","alert",k=>this.rf(k));e.B("runtime","hide-cordova-splash",()=>this.Df());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;h.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const d=e.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",y);d.addEventListener("selectstart",
y);d.addEventListener("gesturehold",y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),d.addEventListener("pointerdown",y)):d.addEventListener("touchstart",y);this.lb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",I,{passive:!1});window.addEventListener("wheel",I,{passive:!1});window.addEventListener("resize",()=>this.Uf());window.addEventListener("fullscreenchange",
()=>this.Va());window.addEventListener("webkitfullscreenchange",()=>this.Va());window.addEventListener("mozfullscreenchange",()=>this.Va());window.addEventListener("fullscreenerror",k=>this.Ec(k));window.addEventListener("webkitfullscreenerror",k=>this.Ec(k));window.addEventListener("mozfullscreenerror",k=>this.Ec(k));e.lc()&&window.addEventListener("focusout",()=>{{const p=document.activeElement;if(p){var k=p.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(p.type.toLowerCase()||"text"):w(p)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.Vf(k);this.Ha=new Set;this.Tb=new WeakSet;this.na=!1}sf(){"cordova"===this.v.C?(document.addEventListener("pause",()=>this.Ic(!0)),document.addEventListener("resume",()=>this.Ic(!1))):document.addEventListener("visibilitychange",()=>this.Ic(document.hidden));return{isSuspended:!(!document.hidden&&!F)}}ed(){window.addEventListener("focus",()=>
this.Xa("window-focus"));window.addEventListener("blur",()=>{this.Xa("window-blur",{parentHasFocus:J()});this.lb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||w(h))&&this.Xa("keyboard-blur")});window.addEventListener("keydown",h=>this.Cd("keydown",h));window.addEventListener("keyup",h=>this.Cd("keyup",h));window.addEventListener("dblclick",h=>this.Gc("dblclick",h,c));window.addEventListener("wheel",h=>this.Hf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.zc(h);this.Wa("pointerdown",h)}),this.v.qa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ob=new self.Le(()=>this.ef(),5),this.ob.Nd=!0,window.addEventListener("pointerrawupdate",h=>this.If(h))):window.addEventListener("pointermove",h=>this.Wa("pointermove",h)),window.addEventListener("pointerup",h=>this.Wa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Wa("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.zc(h);this.Hc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Hc("pointermove",h)),window.addEventListener("mouseup",h=>this.Hc("pointerup",h)),window.addEventListener("touchstart",h=>{this.zc(h);this.Eb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Eb("pointermove",h)),window.addEventListener("touchend",h=>this.Eb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Eb("pointercancel",h)));const e=()=>this.Jc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Xa(e,h){x(this,e,h||null,m)}va(){return this.v.va()}ua(){return this.v.ua()}Uf(){const e=this.va(),h=this.ua();this.Xa("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ra()});this.v.lc()&&(-1!==this.Ma&&clearTimeout(this.Ma),this.Ed(e,h,0))}cg(e,h,d){-1!==this.Ma&&clearTimeout(this.Ma);this.Ma=setTimeout(()=>this.Ed(e,
h,d),48)}Ed(e,h,d){const k=this.va(),l=this.ua();this.Ma=-1;k!=e||l!=h?this.Xa("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ra()}):10>d&&this.cg(k,l,d+1)}Rf(e){this.ad=e.targetOrientation}wg(){const e=this.ad;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Va(){const e=g.Ra();e&&"any"!==this.ad&&this.wg();x(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.va(),innerHeight:this.ua()})}Ec(e){console.warn("[Construct 3] Fullscreen request failed: ",e);x(this,"fullscreenerror",
{isFullscreen:g.Ra(),innerWidth:this.va(),innerHeight:this.ua()})}Ic(e){e?this.v.sc():this.v.Kc();x(this,"visibilitychange",{hidden:e})}Cd(e,h){"Backspace"===h.key&&y(h);const d=b.get(h.code)||h.code;D(this,e,{code:d,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},c)}Hf(e){x(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},c)}Gc(e,h,d){a(h)||D(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},d)}Hc(e,h){if(!a(h)){var d=this.lb;"pointerdown"===e&&0!==d?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");D(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},c);this.lb=h.buttons;this.Gc(h.type,h,f)}}Wa(e,h){if(this.ob&&"pointermove"!==e){var d=this.ob;d.eb||(L(d),d.Qb=Date.now())}d=0;"mouse"===h.pointerType&&(d=this.lb);D(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},c);"mouse"===h.pointerType&&(d="mousemove","pointerdown"===e?d="mousedown":"pointerup"===e&&(d="mouseup"),this.Gc(d,h,f),this.lb=h.buttons)}If(e){this.Vc=e;e=this.ob;if(-1===e.Na){var h=Date.now(),d=h-e.Qb,k=e.Cg;d>=k&&e.Nd?(e.Qb=h,e.eb=!0,e.Mc(),e.eb=!1):e.Na=self.setTimeout(e.ee,Math.max(k-d,4))}}ef(){this.Wa("pointermove",this.Vc);this.Vc=null}Eb(e,h){for(let d=0,k=h.changedTouches.length;d<k;++d){const l=h.changedTouches[d];D(this,e,{pointerId:l.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},c)}}zc(e){window!==window.top&&window.focus();this.Ad(e.target)&&document.activeElement&&!this.Ad(document.activeElement)&&document.activeElement.blur()}Ad(e){return!e||e===document||
e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}We(){this.Kd||(this.Kd=!0,window.addEventListener("deviceorientation",e=>this.yf(e)),window.addEventListener("deviceorientationabsolute",e=>this.zf(e)))}Ve(){this.Jd||(this.Jd=!0,window.addEventListener("devicemotion",e=>this.xf(e)))}yf(e){x(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
c)}zf(e){x(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},c)}xf(e){let h=null;var d=e.acceleration;d&&(h={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var k=e.accelerationIncludingGravity;k&&(d={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});x(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:d,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},
c)}Tf(e){const h=this.v.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Sd&&(h.style.display="",this.Sd=!1)}Ef(e){const h=e.url;e=e.filename;const d=document.createElement("a"),k=document.body;d.textContent=e;d.href=h;d.download=e;k.appendChild(d);d.click();k.removeChild(d)}async Kf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async Cf(e){return await self.C3_GetSvgImageSize(e.blob)}async qf(e){await n(e.url)}Jc(){var e=[...this.Ha];this.Ha.clear();if(!this.na)for(const h of e)(e=h.play())&&e.catch(()=>{this.Tb.has(h)||this.Ha.add(h)})}ta(e){if("function"!==typeof e.play)throw Error("missing play function");this.Tb.delete(e);let h;try{h=e.play()}catch(d){this.Ha.add(e);return}h&&h.catch(()=>{this.Tb.has(e)||this.Ha.add(e)})}Ba(e){this.Ha.delete(e);
this.Tb.add(e)}Ab(e){this.na=!!e}Df(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}wf(e){if(e.show){this.xa||(this.xa=document.createElement("div"),this.xa.id="inspectOutline",document.body.appendChild(this.xa));var h=this.xa;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Lf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Dd(e){window.c3_postToMessagePort&&
(e.from="runtime",window.c3_postToMessagePort(e))}mf(e,h){return this.v.pd(this.Za,"js-invoke-function",{name:e,params:h},void 0,void 0)}rf(e){alert(e.message)}Vf(e){"entered-fullscreen"===e?(g.Id(!0),this.Va()):"exited-fullscreen"===e?(g.Id(!1),this.Va()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function Q(g){if(g.Bg)throw Error("already initialised");g.Bg=!0;var a=g.Xb.yc("dispatchworker.js");g.Oc=await g.Xb.dc(a,g.F,{name:"DispatchWorker"});a=new MessageChannel;g.Sc=a.port1;g.Oc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.Zc=await S(g)}function R(g){return[g.Sc,g.Zc]}
async function S(g){const a=g.Td.length;var b=g.Xb.yc("jobworker.js");b=await g.Xb.dc(b,g.F,{name:"JobWorker"+a});const c=new MessageChannel,f=new MessageChannel;g.Oc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":f.port2},[c.port2,f.port2]);g.Td.push(b);return f.port1}
self.He=class{constructor(g){this.Xb=g;this.F=g.F;this.F="preview"===g.C?this.F+"c3/workers/":this.F+g.Yb;this.Eg=Math.min(navigator.hardwareConcurrency||2,16);this.Oc=null;this.Td=[];this.Zc=this.Sc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ta({Rg:!0,Sg:"workermain.js",Oa:["scripts/c3runtime.js"],he:[],ge:"",Og:"scripts/",dd:["box2d.wasm.js"],fe:"html5"}));"use strict";
{function g(a){a.stopPropagation()}self.Ta.tb(class extends self.jd{constructor(a){super(a,"button")}cc(a,b){const c=document.createElement("input");var f=c;b.isCheckbox?(c.type="checkbox",f=document.createElement("label"),f.appendChild(c),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):c.type="button";f.style.position="absolute";f.addEventListener("touchstart",
g);f.addEventListener("touchmove",g);f.addEventListener("touchend",g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",g);f.addEventListener("keyup",g);c.addEventListener("click",()=>P(this,"click",a,{isChecked:c.checked}));b.id&&(c.id=b.id);this.Ua(f,b);return f}yd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}wc(a){return this.yd(a)}Ua(a,b){const c=this.yd(a);c.checked=b.isChecked;c.disabled=!b.isEnabled;a.title=b.title;a===c?c.value=b.text:
a.lastChild.textContent=b.text}})}"use strict";
{const g=180/Math.PI;self.da=class extends self.ec{constructor(a){super(a,"audio");this.Mb=this.f=null;this.Ob=this.Rc=!1;this.pa=()=>this.xg();this.ba=[];this.D=[];this.ga=null;this.Ud="";this.Vd=-1;this.nb=new Map;this.Wc=1;this.na=!1;this.bd=0;this.$b=1;this.Pc=0;this.Xd="HRTF";this.Od="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.Qd=this.$c=!1;this.ce=this.v.Ge();this.ca=new Map;this.Ea=new Set;this.Tc=!1;this.Xc="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Gf(b,c);this.Lb=null;
self.C3Audio_GetOutputStream=()=>this.Bf();self.C3Audio_DOMInterface=this;H(this,[["create-audio-context",b=>this.af(b)],["play",b=>this.Xf(b)],["stop",b=>this.ug(b)],["stop-all",()=>this.vg()],["set-paused",b=>this.ng(b)],["set-volume",b=>this.sg(b)],["fade-volume",b=>this.ff(b)],["set-master-volume",b=>this.lg(b)],["set-muted",b=>this.mg(b)],["set-silent",b=>this.pg(b)],["set-looping",b=>this.kg(b)],["set-playback-rate",b=>this.og(b)],["seek",b=>this.dg(b)],["preload",b=>this.Yf(b)],["unload",b=>
this.yg(b)],["unload-all",()=>this.zg()],["set-suspended",b=>this.qg(b)],["add-effect",b=>this.ud(b)],["set-effect-param",b=>this.hg(b)],["remove-effects",b=>this.$f(b)],["tick",b=>this.Sf(b)],["load-state",b=>this.Fc(b)]])}async af(a){a.isiOSCordova&&(this.$c=!0);this.bd=a.timeScaleMode;this.Xd=["equalpower","HRTF","soundfield"][a.panningModel];this.Od=["linear","inverse","exponential"][a.distanceModel];this.Yd=a.refDistance;this.Wd=a.maxDistance;this.$d=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ce||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.vd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.vd()};this.Mb=this.f.createGain();this.Mb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.fc();try{await Promise.all(a.preloadList.map(c=>this.Cb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}vd(){this.Ob||(this.Rc=!1,window.addEventListener("pointerup",this.pa,!0),window.addEventListener("touchend",this.pa,!0),window.addEventListener("click",this.pa,!0),window.addEventListener("keydown",this.pa,!0),this.Ob=!0)}cf(){this.Ob&&(this.Rc=!0,window.removeEventListener("pointerup",this.pa,!0),window.removeEventListener("touchend",
this.pa,!0),window.removeEventListener("click",this.pa,!0),window.removeEventListener("keydown",this.pa,!0),this.Ob=!1)}xg(){if(!this.Rc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.cf()}}W(){return this.f}fc(){return this.f.currentTime}ra(){return this.Mb}ld(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.ra()}ie(a,b){a=a.toLowerCase();let c=this.ca.get(a);
c||(c=[],this.ca.set(a,c));b.jg(c.length);b.rg(a);c.push(b);this.Gd(a)}Gd(a){let b=this.ra();const c=this.ca.get(a);if(c&&c.length){b=c[0].P();for(let f=0,m=c.length;f<m;++f){const n=c[f];f+1===m?n.S(this.ra()):n.S(c[f+1].P())}}for(const f of this.la(a))f.Me(b);this.ya&&this.Xc===a&&(this.ya.disconnect(),this.ya.connect(b))}wb(){return this.Wc}xb(){return this.na}ig(){this.Qd=!0}Ae(a,b){return b?this.v.Ag(a).then(c=>{const f=this.f.createBuffer(1,c.length,48E3);f.getChannelData(0).set(c);return f}):
new Promise((c,f)=>{this.f.decodeAudioData(a,c,f)})}ta(a){this.v.ta(a)}Ba(a){this.v.Ba(a)}qd(a){let b=0;for(let c=0,f=this.D.length;c<f;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Ne(){let a=0;for(let b=0,c=this.ba.length;b<c;++b){const f=this.ba[b];this.ba[a]=f;f.sa()?f.c():++a}this.ba.length=a}*la(a){if(a)for(const b of this.D)self.da.Be(b.$,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Cb(a,b,c,f,m){for(const n of this.ba)if(n.Qa()===b)return await T(n),
n;if(m)return null;f&&(this.$c||this.Qd)&&this.Ne();m="audio/webm; codecs=opus"===c&&!this.ce;f&&m&&this.ig();a=!f||this.$c||m?new self.we(this,a,b,c,f,m):new self.ue(this,a,b,c,f);this.ba.push(a);await T(a);return a}async vc(a,b,c,f,m){for(const n of this.D)if(n.Qa()===b&&(n.bc()||m))return n.Pe(f),n;a=await this.Cb(a,b,c,m);f="html5"===a.Lc?new self.ve(a.i,a,f):new self.xe(a.i,a,f);this.D.push(f);return f}Te(a){let b=this.nb.get(a);if(!b){let c=null;b={cd:0,promise:new Promise(f=>c=f),resolve:c};
this.nb.set(a,b)}b.cd++}ag(a){const b=this.nb.get(a);if(!b)throw Error("expected pending tag");b.cd--;0===b.cd&&(b.resolve(),this.nb.delete(a))}rc(a){a||(a=this.Ud);return(a=this.nb.get(a))?a.promise:Promise.resolve()}Db(){if(0<this.Ea.size)K(this);else for(const a of this.D)if(a.md()){K(this);break}}Ca(){for(var a of this.Ea)a.Ca();a=this.fc();for(var b of this.D)b.Ca(a);b=this.D.filter(c=>c.md()).map(c=>c.Pa());x(this,"state",{tickCount:this.Vd,audioInstances:b,analysers:[...this.Ea].map(c=>c.De())});
0===b.length&&0===this.Ea.size&&this.Pb&&(this.v.bg(this.de),this.Pb=!1)}nc(a,b,c){x(this,"trigger",{type:a,tag:b,aiid:c})}async Xf(a){const b=a.originalUrl,c=a.url,f=a.type,m=a.isMusic,n=a.tag,u=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Ud=n;this.Te(n);try{this.ga=await this.vc(b,c,f,n,m),v?(this.ga.zb(!0),this.ga.Oe(v.x,
v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ga.Qe(v.uid)):this.ga.zb(!1),this.ga.Play(u,A,B,w)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.ag(n)}K(this)}ug(a){a=a.tag;for(const b of this.la(a))b.ma()}vg(){for(const a of this.D)a.ma()}ng(a){const b=a.tag;a=a.paused;for(const c of this.la(b))a?c.Sa():c.yb();this.Db()}sg(a){const b=a.tag;a=a.vol;for(const c of this.la(b))c.Bb(a)}async ff(a){const b=a.tag,c=a.vol,
f=a.duration;a=a.stopOnEnd;await this.rc(b);for(const m of this.la(b))m.Ce(c,f,a);this.Db()}lg(a){this.Wc=a.vol;for(const b of this.D)b.Ib()}mg(a){const b=a.tag;a=a.isMuted;for(const c of this.la(b))c.rd(a)}pg(a){this.na=a.isSilent;this.v.Ab(this.na);for(const b of this.D)b.Hb()}kg(a){const b=a.tag;a=a.isLooping;for(const c of this.la(b))c.pc(a)}async og(a){const b=a.tag;a=a.rate;await this.rc(b);for(const c of this.la(b))c.td(a)}async dg(a){const b=a.tag;a=a.pos;await this.rc(b);for(const c of this.la(b))c.oc(a)}async Yf(a){const b=
a.originalUrl,c=a.url,f=a.type;a=a.isMusic;try{await this.vc(b,c,f,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async yg(a){if(a=await this.Cb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}zg(){for(const a of this.ba)a.c();this.ba.length=0}qg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.qc(a);a&&this.f.suspend&&this.f.suspend()}Sf(a){this.$b=a.timeScale;this.Pc=a.gameTime;this.Vd=a.tickCount;if(0!==
this.bd)for(var b of this.D)b.Da();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const f of this.D)f.fa===a&&f.sd(c.x,c.y,c.angle)}}async ud(a){var b=a.type;const c=a.tag;var f=a.params;if("filter"===b)f=new self.oe(this,...f);else if("delay"===b)f=new self.me(this,...f);else if("convolution"===b){b=null;try{b=await this.Cb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}f=new self.le(this,b.aa,...f);f.fg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.pe(this,...f);else if("phaser"===b)f=new self.re(this,...f);else if("gain"===b)f=new self.qe(this,...f);else if("tremolo"===b)f=new self.te(this,...f);else if("ringmod"===b)f=new self.se(this,...f);else if("distortion"===b)f=new self.ne(this,...f);else if("compressor"===b)f=new self.ke(this,...f);else if("analyser"===b)f=new self.je(this,...f);else throw Error("invalid effect type");this.ie(c,
f);this.Fd()}hg(a){const b=a.index,c=a.param,f=a.value,m=a.ramp,n=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,f,m,n),this.Fd())}$f(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const c of b)c.c();this.ca.delete(a);this.Gd(a)}}Se(a){this.Ea.add(a);this.Db()}Zf(a){this.Ea.delete(a)}Fd(){this.Tc||(this.Tc=!0,Promise.resolve().then(()=>this.df()))}df(){const a={};for(const [b,c]of this.ca)a[b]=c.map(f=>f.Pa());x(this,"fxstate",{fxstate:a});this.Tc=!1}async Fc(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.sa()&&1===b||(c.sa()||2!==b)&&c.ma();for(const f of this.ca.values())for(const m of f)m.c();this.ca.clear();this.$b=a.timeScale;this.Pc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.na=a.isSilent;this.v.Ab(this.na);this.Wc=a.masterVolume;c=[];for(const f of Object.values(a.effects))c.push(Promise.all(f.map(m=>this.ud(m))));await Promise.all(c);await Promise.all(a.playing.map(f=>this.nf(f,b)));this.Db()}async nf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,f=a.bufferUrl,m=a.bufferType,n=a.isMusic,u=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!n||1!==b)if(n||2!==b){b=null;try{b=await this.vc(c,f,m,u,n)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Ke(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Sa();b.Bc(a)}}}Gf(a,b){this.ya&&this.ya.disconnect();this.Xc=b.toLowerCase();this.ya=this.f.createMediaStreamSource(a);this.ya.connect(this.ld(this.Xc))}Bf(){this.Lb||(this.Lb=this.f.createMediaStreamDestination(),
this.Mb.connect(this.Lb));return this.Lb.stream}static Be(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Re(a){return a*g}static ze(a){return Math.pow(10,a/20)}static kd(a){return Math.max(Math.min(self.da.ze(a),1),0)}static Je(a){return Math.log(a)/Math.log(10)*20}static Ie(a){return self.da.Je(Math.max(Math.min(a,1),0))}static Kg(a,b){return 1-Math.exp(-b*a)}};self.Ta.tb(self.da)}"use strict";function T(g){g.Rb||(g.Rb=g.Ac());return g.Rb}
self.fd=class{constructor(g,a,b,c,f){this.i=g;this.Gg=a;this.za=b;this.R=c;this.Dg=f;this.Lc="";this.Rb=null}c(){this.Rb=this.i=null}Ac(){}W(){return this.i.W()}ic(){return this.Gg}Qa(){return this.za}hc(){return this.R}sa(){return this.Dg}ea(){}};"use strict";
self.ue=class extends self.fd{constructor(g,a,b,c,f){super(g,a,b,c,f);this.Lc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.hb=this.ib=null;this.J.addEventListener("canplaythrough",()=>!0);this.mb=this.W().createGain();this.kb=null;this.J.addEventListener("canplay",()=>{this.ib&&(this.ib(),this.hb=this.ib=null);!this.kb&&this.J&&(this.kb=this.W().createMediaElementSource(this.J),this.kb.connect(this.mb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.za}' error: `,m);this.hb&&(this.hb(m),this.hb=this.ib=null)})}c(){this.i.qd(this);this.mb.disconnect();this.mb=null;this.kb.disconnect();this.kb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Ac(){return new Promise((g,a)=>{this.ib=g;this.hb=a;this.J.src=this.za})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function U(g){if(g.wa)return g.wa;var a=g.i.v;if("cordova"===a.C&&a.nd(g.za)&&"file:"===location.protocol)g.wa=await a.ub(g.za);else{a=await fetch(g.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.wa=await a.arrayBuffer()}}async function W(g){if(g.aa)return g.aa;g.aa=await g.i.Ae(g.wa,g.Fg);g.wa=null}
self.we=class extends self.fd{constructor(g,a,b,c,f,m){super(g,a,b,c,f);this.Lc="webaudio";this.aa=this.wa=null;this.Fg=!!m}c(){this.i.qd(this);this.aa=this.wa=null;super.c()}async Ac(){try{await U(this),await W(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.za}': `,g)}}ea(){return this.aa?this.aa.duration:0}};"use strict";
{let g=0;self.gd=class{constructor(a,b,c){this.i=a;this.L=b;this.$=c;this.Jb=g++;this.M=this.W().createGain();this.M.connect(this.ra());this.A=null;this.fb=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.H=!0;this.V=this.ka=this.G=!1;this.qb=1;this.Fa=!1;this.Z=1;a=this.i.bd;this.Uc=1===a&&!this.sa()||2===a;this.bb=this.fa=-1;this.be=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ra(){return this.i.ld(this.$)}wb(){return this.i.wb()}vb(){return this.Uc?
this.i.Pc:performance.now()/1E3}ic(){return this.L.ic()}Qa(){return this.L.Qa()}hc(){return this.L.hc()}sa(){return this.L.sa()}Pe(a){this.$=a}T(){}bc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}md(){return!this.H&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}ma(){}Sa(){}yb(){}Bb(a){this.qb=a;this.M.gain.cancelScheduledValues(0);this.bb=-1;this.M.gain.value=this.jc()}Ce(a,b,c){if(!this.Fa){a*=this.wb();var f=this.M.gain;f.cancelScheduledValues(0);var m=this.i.fc();b=m+b;f.setValueAtTime(f.value,
m);f.linearRampToValueAtTime(a,b);this.qb=a;this.bb=b;this.be=c}}Ib(){this.Bb(this.qb)}Ca(a){-1!==this.bb&&a>=this.bb&&(this.bb=-1,this.be&&this.ma(),this.i.nc("fade-ended",this.$,this.Jb))}jc(){const a=this.qb*this.wb();return isFinite(a)?a:0}rd(a){a=!!a;this.Fa!==a&&(this.Fa=a,this.Hb())}xb(){return this.i.xb()}Hb(){}pc(){}td(a){this.Z!==a&&(this.Z=a,this.Da())}Da(){}oc(){}qc(){}zb(a){a=!!a;this.fb!==a&&((this.fb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Xd,this.A.distanceModel=
this.i.Od,this.A.refDistance=this.i.Yd,this.A.maxDistance=this.i.Wd,this.A.rolloffFactor=this.i.$d),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.ra())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.ra())))}Oe(a,b,c,f,m,n){this.fb&&(this.sd(a,b,c),a=self.da.Re,this.A.coneInnerAngle=a(f),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=n)}sd(a,b,c){this.fb&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(c),this.ia[1]=Math.sin(c),this.ia[2]=0,this.A.setPosition(...this.ja),
this.A.setOrientation(...this.ia))}Qe(a){this.fa=a}kc(){}Me(a){const b=this.A||this.M;b.disconnect();b.connect(a)}Pa(){return{aiid:this.Jb,tag:this.$,duration:this.ea(),volume:this.qb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.Z,uid:this.fa,bufferOriginalUrl:this.ic(),bufferUrl:"",bufferType:this.hc(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Fa,resumePosition:this.kc(),pan:this.Ee()}}Bc(a){this.td(a.playbackRate);this.rd(a.isMuted)}Ee(){if(!this.A)return null;const a=
this.A;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Ke(a){if(a){this.zb(!0);a=this.A;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.zb(!1)}}}"use strict";
self.ve=class extends self.gd{constructor(g,a,b){super(g,a,b);this.L.mb.connect(this.M);this.L.onended=()=>this.Dc()}c(){this.ma();this.L.mb.disconnect();super.c()}O(){return this.L.O()}Dc(){this.H=!0;this.fa=-1;this.i.nc("ended",this.$,this.Jb)}T(){return this.O().ended}bc(){return this.H?!0:this.T()}Aa(g){let a=this.O().currentTime;g&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(g,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==g&&(c.loop=g);this.Bb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.L.Qa()}' to position '${b}': `,f)}this.i.ta(c);this.G=this.H=!1;this.V=g;this.Z=1}ma(){const g=this.O();g.paused||g.pause();this.i.Ba(g);this.H=!0;this.G=!1;this.fa=-1}Sa(){if(!(this.G||this.H||this.T())){var g=this.O();g.paused||g.pause();this.i.Ba(g);this.G=!0}}yb(){!this.G||this.H||this.T()||(this.i.ta(this.O()),this.G=!1)}Hb(){this.O().muted=this.Fa||this.xb()}pc(g){g=!!g;
this.V!==g&&(this.V=g,this.O().loop=g)}Da(){let g=this.Z;this.Uc&&(g*=this.i.$b);try{this.O().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}oc(g){if(!this.H&&!this.T())try{this.O().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}kc(){return this.Aa()}qc(g){g?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.ta(this.O()),this.ka=!1)}};"use strict";
function X(g){g.j&&g.j.disconnect();g.j=null;g.Ya=null}
self.xe=class extends self.gd{constructor(g,a,b){super(g,a,b);this.j=null;this.Ub=c=>this.Dc(c);this.Qc=!0;this.Ya=null;this.N=this.Zb=0;this.Yc=1}c(){this.ma();X(this);this.Ub=null;super.c()}Dc(g){this.G||this.ka||g.target!==this.Ya||(this.H=this.Qc=!0,this.fa=-1,X(this),this.i.nc("ended",this.$,this.Jb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Qc}bc(){return!this.j||this.H?!0:this.T()}Aa(g){let a;a=this.G?this.N:this.vb()-this.Zb;g&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(g,
a,b,c){this.Yc=1;this.Bb(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.aa;this.j.connect(this.M);this.Ya=this.j;this.j.onended=this.Ub;this.j.loop=g;this.j.start(c,b);this.G=this.H=this.Qc=!1;this.V=g;this.Z=1;this.Zb=this.vb()-b}ma(){if(this.j)try{this.j.stop(0)}catch(g){}this.H=!0;this.G=!1;this.fa=-1}Sa(){this.G||this.H||this.T()||(this.N=this.Aa(!0),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}yb(){!this.G||this.H||this.T()||(X(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.aa,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Ub,this.j.loop=this.V,this.Ib(),this.Da(),this.Zb=this.vb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.G=!1)}jc(){return super.jc()*this.Yc}Hb(){this.Yc=this.Fa||this.xb()?0:1;this.Ib()}pc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Da(){let g=this.Z;this.Uc&&(g*=this.i.$b);this.j&&(this.j.playbackRate.value=g)}oc(g){this.H||this.T()||(this.G?this.N=g:(this.Sa(),this.N=g,this.yb()))}kc(){return this.N}qc(g){g?
this.IsPlaying()?(this.ka=!0,this.N=this.Aa(!0),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Ub,this.j.loop=this.V,this.Ib(),this.Da(),this.Zb=this.vb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.ka=!1)}Bc(g){super.Bc(g);this.N=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.f=a.W();this.Rd=-1;this.R=this.$="";this.g=null}c(){this.f=null}jg(a){this.Rd=a}rg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var m=this.f.currentTime;f+=m;switch(c){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,f)}}}Pa(){return{type:this.R,tag:this.$,params:this.g}}}
self.oe=class extends g{constructor(a,b,c,f,m,n,u){super(a);this.R="filter";this.g=[b,c,f,m,n,u];this.l=this.o();this.b=this.o();this.b.gain.value=u;this.a=this.o();this.a.gain.value=1-u;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=f;this.u.Q.value=m;this.u.gain.vlaue=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,f)}}};self.me=class extends g{constructor(a,b,c,f){super(a);this.R="delay";this.g=[b,c,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.jb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.ab=this.o();this.ab.gain.value=c;this.l.connect(this.jb);this.l.connect(this.a);this.jb.connect(this.b);this.jb.connect(this.U);this.U.connect(this.ab);this.ab.connect(this.jb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.jb.disconnect();this.U.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){const m=self.da.kd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 4:this.g[1]=m(b);this.m(this.ab.gain,m(b),c,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,f)}}};self.le=class extends g{constructor(a,b,c,f){super(a);this.R="convolution";this.g=[c,f];this.Md=this.Ld="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.$a=this.f.createConvolver();this.$a.normalize=c;this.$a.buffer=b;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b)}c(){this.l.disconnect();this.$a.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}fg(a,b){this.Ld=a;this.Md=b}Pa(){const a=
super.Pa();a.bufferOriginalUrl=this.Ld;a.bufferUrl="";a.bufferType=this.Md;return a}};self.pe=class extends g{constructor(a,b,c,f,m,n){super(a);this.R="flanger";this.g=[b,c,f,m,n];this.l=this.o();this.a=this.o();this.a.gain.value=1-n/2;this.b=this.o();this.b.gain.value=n/2;this.cb=this.o();this.cb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.I=this.o();this.I.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.cb);this.cb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,c,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,f);break;case 8:this.g[3]=b/100,this.m(this.cb.gain,b/100,c,f)}}};self.re=class extends g{constructor(a,b,c,f,m,n,u){super(a);this.R="phaser";this.g=[b,c,f,m,n,u];this.l=this.o();this.a=this.o();this.a.gain.value=1-u/2;this.b=this.o();this.b.gain.value=u/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=n;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,f);break;case 6:this.g[3]=b;this.m(this.I.gain,b,c,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,f)}}};self.qe=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,f){const m=self.da.kd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,f)}}};self.te=class extends g{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=c/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,f);this.m(this.I.gain,b/2,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.se=class extends g{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.pb=this.o();this.pb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.pb.gain);this.s.start(0);this.l.connect(this.pb);this.l.connect(this.a);this.pb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.pb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,f);
this.m(this.a.gain,1-b,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.ne=class extends g{constructor(a,b,c,f,m,n){super(a);this.R="distortion";this.g=[b,c,f,m,n];this.l=this.o();this.Wb=this.o();this.Vb=this.o();this.gg(f,m);this.b=this.o();this.b.gain.value=n;this.a=this.o();this.a.gain.value=1-n;this.ac=this.f.createWaveShaper();this.Nc=new Float32Array(65536);this.hf(b,c);this.ac.curve=this.Nc;this.l.connect(this.Wb);this.l.connect(this.a);this.Wb.connect(this.ac);this.ac.connect(this.Vb);
this.Vb.connect(this.b)}c(){this.l.disconnect();this.Wb.disconnect();this.ac.disconnect();this.Vb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}gg(a,b){.01>a&&(a=.01);this.Wb.gain.value=a;this.Vb.gain.value=Math.pow(1/a,.6)*b}hf(a,b){for(let c=0;32768>c;++c){let f=c/32768;f=this.tg(f,a,b);this.Nc[32768+c]=f;this.Nc[32768-c-1]=-f}}tg(a,b,c){c=1.05*c*b-b;const f=0>a?-a:a;return(f<b?f:b+c*self.da.Kg(f-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}};self.ke=class extends g{constructor(a,b,c,f,m,n){super(a);this.R="compressor";this.g=[b,c,f,m,n];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=f;this.h.attack.value=m;this.h.release.value=n}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.je=class extends g{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Pd=new Float32Array(this.h.frequencyBinCount);this.ae=new Uint8Array(b);this.Zd=this.Ia=0;this.i.Se(this)}c(){this.i.Zf(this);this.h.disconnect();super.c()}Ca(){this.h.getFloatFrequencyData(this.Pd);this.h.getByteTimeDomainData(this.ae);const a=this.h.fftSize;let b=this.Ia=0;for(var c=0;c<a;++c){let f=(this.ae[c]-128)/128;0>f&&(f=-f);
this.Ia<f&&(this.Ia=f);b+=f*f}c=self.da.Ie;this.Ia=c(this.Ia);this.Zd=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}De(){return{tag:this.$,index:this.Rd,peak:this.Ia,rms:this.Zd,binCount:this.h.frequencyBinCount,freqBins:this.Pd}}}}"use strict";
{function g(a){a.stopPropagation()}self.Ta.tb(class extends self.jd{constructor(a){super(a,"list");O(this,"set-selected-index",(b,c)=>this.Qf(b,c.selectedIndex));O(this,"add-item",(b,c)=>this.pf(b,c));O(this,"remove-item",(b,c)=>this.Mf(b,c));O(this,"set-item",(b,c)=>this.Pf(b,c));O(this,"clear",b=>this.tf(b));O(this,"load-state",(b,c)=>this.Fc(b,c))}cc(a,b){const c=b.isDropdown,f=b.isMultiSelect,m=b.items,n=document.createElement("select");n.style.position="absolute";n.style.userSelect="none";n.style.webkitUserSelect=
"none";n.multiple=f;c||(n.size=2);for(const u of m)n.add(this.uc(u));n.addEventListener("touchstart",g);n.addEventListener("touchmove",g);n.addEventListener("touchend",g);n.addEventListener("mousedown",g);n.addEventListener("mouseup",g);n.addEventListener("click",u=>{u.stopPropagation();P(this,"click",a,this.xc(n))});n.addEventListener("dblclick",u=>{u.stopPropagation();P(this,"dblclick",a,this.xc(n))});n.addEventListener("change",()=>N(this,"change",a,this.xc(n)));b.id&&(n.id=b.id);this.Ua(n,b);
return n}uc(a){const b=document.createElement("option");b.text=a;return b}xc(a){const b=a.selectedIndex,c=[];for(let f=0,m=a.length;f<m;++f)a.options[f].selected&&c.push(f);return{selectedIndex:b,selectedIndices:c}}Ua(a,b){a.title=b.title;a.disabled=!b.isEnabled;a.multiple=!!b.isMultiSelect}Qf(a,b){a.selectedIndex=b}pf(a,b){const c=b.index;b=this.uc(b.text);0>c?a.add(b):a.add(b,c)}Mf(a,b){a.remove(b.index)}Pf(a,b){a.options[b.index].text=b.text}tf(a){a.innerHTML=""}Fc(a,b){a.innerHTML="";for(const c of b.items)a.add(this.uc(c));
a.selectedIndex=b.selectedIndex;for(const c of b.selectedIndices)if(b=a.options[c])b.selected=!0}})};
